blank_issues_enabled: false
contact_links:
  - name: Issue with plugin
    url: https://github.com/MinersStudios/WhoMine/issues/new/choose
    about: Please open issues relating to plugin in MinersStudios/WhoMine
  - name: 🌐 Website
    url: https://whomine.net/
    about: Check out our website
  - name: 📖 Docs
    url: https://docs.whomine.net/
    about: Could be useful for basic player questions
  - name: 💬 Discord
    url: https://discord.whomine.net/
    about: Join our Discord server, questions are answered faster here
